---
- name: get the hostname
  shell: raspi-config nonint get_hostname
  register: current_hostname
  changed_when: false
  failed_when: current_hostname.stderr != ""

- name: set the hostname
  shell: raspi-config nonint do_hostname {{ network_hostname }}
  when: current_hostname.stdout != network_hostname
  notify:
  - reboot
  - set the new host ssh address
  - wait for reboot to finish

- name: assign a fixed IP address
  blockinfile:
    path: /etc/dhcpcd.conf
    state: present
    insertafter: EOF
    block: |
      interface {{ network_interface }}
      static ip_address={{ network_ip_address }}
      static routers={{ network_router_ip_address }}
      static domain_name_servers={{ network_dns_ip_address }}

- name: get wifi country
  shell: raspi-config nonint get_wifi_country
  register: current_wifi_country
  changed_when: false
  failed_when: current_wifi_country.stderr != ""

- name: set wifi country
  shell: raspi-config nonint do_wifi_country {{ wifi_country }}
  when: current_wifi_country.rc in [0, 1] and  current_wifi_country.stdout != wifi_country
