---
- name: install the SSH public key
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', ssh_key_file) }}"

- name: change the 'pi' user password
  user: name=pi password={{new_password}}

- name: set the new Ansible ssh password
  set_fact:
    ansible_ssh_pass:
