---
- name: reboot
  shell: sleep 3 ; shutdown -r now 'Ansible reboot'
  ignore_errors: true
  changed_when: false
  async: 1
  poll: 0

- name: set the new host ssh address
  set_fact:
    ansible_host: "{{ network_ip_address }}"

- name: wait for reboot to finish
  wait_for_connection:
    timeout: 120
    delay: 60
